version: "3.8"

services:

  #-------------------- ODOO --------------------
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}

    depends_on:
      - db

    ports:
      - "${WEB_PORT}:8069"

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  #----------------------------------------------


  #-------------------- POSTGRES --------------------
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_db
      - POSTGRES_USER=odoo_db
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    #--------------------------------------------------

volumes:
  odoo-db-data:
  odoo-web-data:
